### ISSUE TITLE
.ico not converting when using MiniMagick

### ISSUE THREAD

**Issue by arthurnn** [carrierwaveuploader/carrierwave#1069]
Gist with info: https://gist.github.com/arthurnn/5400503

Using the uploader on the gist, When I try to store the favicon:

``` ruby
file = File.open(Rails.root.join('spec','fixtures','assets', 'screenshot.png'))
uploader = FaviconLogosUploader.new
uploader.store!(file)
```

I get an error(which is on the same gist).

After debugging it, I am pretty sure that the issue is on the `manipulate!` method in https://github.com/jnicklas/carrierwave/blob/master/lib/carrierwave/processing/mini_magick.rb#L257 , I guess that should receive an format option, same as rmagick.rb file. Because when MiniMagick try to write to a file with a different extension it doesnt work, in case that the file is now a .ico file.

related https://github.com/minimagick/minimagick/issues/70

**Comment by adrianscott83** [comment]
I just wanted to leave a comment about how I got this working (as there's no solution listed above).  Basically, as discussed, CarrierWave's `manipulate!` method first changes the format of the image and then saves it with its previous name.

Normally it will perform a `CarrierWave::SanitizedFile.move_to` command after this, but in the case of .ico files, it'll fail because MiniMagick cannot write out an ico file with an extension that isn't ico.

The trick is to move the file _before_ doing the processing:

```ruby
def iconify
  cache_stored_file! if !cached?
  image = ::MiniMagick::Image.open(current_path)

  begin
    # Move first
    new_path = current_path.chomp(File.extname(current_path)) + ".ico"
    file.move_to(new_path, permissions, directory_permissions)
    
    # Resize to a 32x32 square and convert to an ico file
    image.resize("32x32>")
    image.resize("32x32<")
    image.format("ico")
    image.write(current_path)

    image.run_command("identify", current_path)
  ensure
    image.destroy!
  end
rescue ::MiniMagick::Error, ::MiniMagick::Invalid => e
  default = I18n.translate(:"errors.messages.mini_magick_processing_error", :e => e, :locale => :en)
  message = I18n.translate(:"errors.messages.mini_magick_processing_error", :e => e, :default => default)
  raise CarrierWave::ProcessingError, message
end
```

Which can then be invoked the usual way as one of your CarrierWave variants:

```ruby
version :ico do
  process :iconify
end
```

**Comment by eveevans** [comment]
But this will generate a non 'ico' file extension.
