### ISSUE TITLE
resubmitting with cache

### ISSUE THREAD

**Issue by ghost** [carrierwaveuploader/carrierwave#1086]
When I submit an image via Carrierwave, and am missing one field (i.e. the title), then the cached image will appear...

```
  <% if @post.avatar? %>
      <%= image_tag @post.avatar_url, :style => "width:300px"  %> 
      <%= f.hidden_field :avatar_cache %>
      <%= @post.avatar_url %>
  <% end %>
```

However, the :avatar_cache field is empty. When I resubmit the form, none of the image properties move forward, so I have to reselect the image.

The issue is similar to this. http://stackoverflow.com/questions/16431089/carrierwave-cache-not-resubmitting

What is happening? Thank you.

**Comment by edatrix** [comment]
how could i provide the value to a nested field?  everything i find points to this (in addition to whitelisting the hidden fields, etc.), but i can't get it to work so that cached fields in nested forms rerender post-validation errors.

(and as an additional caveat, this occurs only on "create", not on "edit".)
