### ISSUE TITLE
Separating 'fog_public' responsibility

### ISSUE THREAD

**Issue by denzel-morris** [carrierwaveuploader/carrierwave#1215]
## The Issue

Firstly, I am aware of this issue https://github.com/carrierwaveuploader/carrierwave/issues/1158#issuecomment-21812948, but while my issue is related, it is slightly different.

Currently the _fog_public_ configuration variable is used both for uploading:
https://github.com/carrierwaveuploader/carrierwave/blob/master/lib/carrierwave/storage/fog.rb#L264
And for the downloadable URL, as referenced by the issue above:
https://github.com/carrierwaveuploader/carrierwave/blob/master/lib/carrierwave/storage/fog.rb#L322
## Proposed Solution

I'd like to separate the responsibility of _fog_public_ into _fog_serve_public_ and _fog_upload_public_ (or similarly named configuration variables).

Would anyone be open to a pull request for this use case? If so, I can write one up and submit it, otherwise I will continue to use my own fork of CarrierWave until this issue is resolved.
## Example Use Case

I am uploading a set of files to S3 that I want kept private, however a small subset of files can be served with public CloudFront URLs from S3.

As you can see if _fog_public_ is **true** then the CloudFront _asset_host_ will be used, but all S3 source files will be publicly available. On the other hand, if _fog_public_ is **false** then the CloudFront _asset_host_ will not be used, and all S3 source files will be private.

**Comment by nisanth074** [comment]
I'm working on a pull request. As @DenzelMorris suggested, I wish to split `fog_public` into two options, `fog_serve_public` and `fog_upload_public`. To maintain backward compatibility, I plan to change `Uploader#fog_public=`, `Uploader#fog_public` to
```ruby
class Uploader
  def fog_public=(value)
    self.fog_upload_public = value
    self.fog_serve_public = value
  end

  def fog_public
    self.fog_upload_public && self.fog_serve_public
  end
end
```

@bensie Thoughts?

## My Use Case
Here's the issue I faced last month. We upload all our files to s3 as private files. We use s3's bucket policies (instead of ACLs) to make files publicly available. If I set `config.fog_public` as false,
```ruby
CarrierWave.configure do |config|
  config.fog_public = false
end
```
accessing a file's url generates an authenticated s3 url even though these files are publicly available via s3 bucket policies. Instead, I'd to like to configure carrierwave as
```ruby
CarrierWave.configure do |config|
  config.fog_upload_public = false
  config.fog_serve_public = true
end
```

**Comment by lukeasrodgers** [comment]
@nisanth074 did you ever end up completing/opening the PR you mention? I require similar functionality to accommodate the fact that AWS does not permit an IAM user to specify an ACL (http://docs.aws.amazon.com/AmazonS3/latest/dev/acl-overview.html#specifying-grantee), so PUTs that involve any ACL header result in a 403, but I don't want to get private URLs when serving said objects.
