### ISSUE TITLE
undefined method mounted_column_changed? for object

### ISSUE THREAD

**Issue by jwoertink** [carrierwaveuploader/carrierwave#1301]
Using rails 3 for a User avatar you could check if that avatar changed with the `_changed?`. I'm in middle of an upgrade to rails 4, and I'm getting an undefined method for this now.

``` ruby
class User
  include Mongoid::Document
  mount_uploader :avatar, AvatarUploader
end

class AvatarUploader < CarrierWave::Uploader::Base
  include CarrierWave::MiniMagick
  version :large do
    process :resize_to_fill => [640, 640]
  end
  # ...
end
```

In console I can run

``` ruby
user = User.first
#=> #<User _id: ....
user.avatar
#=> #<AvatarUploader: ....
user.avatar_changed?
#=> NoMethodError: undefined method `avatar_changed?' for #<User:0x007fad2eef5140>
```

Using Rails 4.0.2 and Carrierwave 0.9.0

**Comment by toobulkeh** [comment]
I'm running into this problem when running old migrations on objects that didn't use to have CarrierWave mounted to it, but now do -- so the codebase and the migrations are out of sync.

It seems like something in a callback or validation step -- though skipping validations does not help.
If this is a callback, then which should I skip?

Another solution is to just update the columns instead of using `.save`s in my migrations from here on out....
