### ISSUE TITLE
Url generation doesn't work if asset_host passed as a block.

### ISSUE THREAD

**Issue by dpisarewski** [carrierwaveuploader/carrierwave#1343]
I wanted to define a dynamic asset host using this code to generate full image urls:

```ruby
config.action_controller.asset_host = Proc.new { |source, request|
  "#{request.protocol}#{request.host_with_port}"
}
```

I tried [this solution on Stackoverflow](http://stackoverflow.com/questions/5484809/full-url-for-an-image-path-in-rails-3#answer-15011797)

Unfortunately it doesn't work with the block syntax because Carrierwave passes the uploader object instead of source and request objects to the block and I get following error message:
```
NoMethodError: undefined method `protocol' for nil:NilClass
```

See [Carrierwave code](https://github.com/carrierwaveuploader/carrierwave/blob/master/lib/carrierwave/uploader/configuration.rb#L136)

**Comment by jgillman** [comment]
:+1: Didn't realize this was still an open issue. Without this it's very difficult to have a dynamic asset host. In my particular use case, I want to split requests between two hosts to gain more concurrent requests. I would do this by hashing the requested path (or something otherwise unique) so the same asset is always loaded from the same CDN and can be cached by the browser.

```ruby
config.asset_host = Proc.new { |source, request|
  index = source.hash % ASSET_CDN_DOMAINS.count
  "https://#{ ASSET_CDN_DOMAINS[index] }"
}
```

*Where ASSET_CDN_DOMAINS is an array of available domains.*

**Comment by taco-chen** [comment]
+1
It would be very helpful!

**Comment by thomasfedb** [comment]
If `asset_host` responds to `call` then it will be called with the file in question. We don't pass the request when calling `asset_host`.

I would not support doing so without very good reason. Particularly because Carrierwave isn't restricted to being used purely during Rails requests. For example, Carrierwave uploads might be accessed by rake tasks, or by job workers.

Further the mechanism required to pass the current request when calling `asset_host` is non-trivial and inelegant. We'd need a very good reason to consider it.

Rather, you'd be better off using the file's `path` attribute and generating the desired URL in a helper or model presenter.
