### ISSUE TITLE
Fails silently when using remote URL with invalid SSL certificate

### ISSUE THREAD

**Issue by ethnt** [carrierwaveuploader/carrierwave#1428]
I've been running into issues with using remote files with invalid SSL certificates. Here is an example model:

``` ruby
# app/models/product.rb

class Product
  include Mongoid::Document

  mount_uploader :photo, PhotoUploader
end
```

And an uploader:

``` ruby
# app/uploaders/photo_uploader.rb

class PhotoUploader < CarrierWave::Uploader::Base
  storage :file
end
```

If, for example, I try to use [this image](https://s7.jcrew.com/is/image/jcrew/03226_GR6414?$pdp_fs418$) as a remote file to upload, I do this:

```
p = Product.new
p.remote_photo_url = 'https://s7.jcrew.com/is/image/jcrew/03226_GR6414?$pdp_fs418$'
p.save # => true
```

I can tell this image is on a host with an expired certificate by just using wget:

```
$ wget https://s7.jcrew.com/is/image/jcrew/27156_WT0002_m?$pdp_fs418$
--2014-07-27 10:47:39--  https://s7.jcrew.com/is/image/jcrew/27156_WT0002_m?$
Resolving s7.jcrew.com... 23.207.54.111
Connecting to s7.jcrew.com|23.207.54.111|:443... connected.
ERROR: cannot verify s7.jcrew.com's certificate, issued by '/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert High Assurance CA-3':
  Issued certificate has expired.
To connect to s7.jcrew.com insecurely, use `--no-check-certificate'.
```

This does not fail, but when I look for the file that was downloaded and then uploaded, it does not exist:

```
p.photo # => nil
```

I was able to circumvent this by telling OpenSSL to ignore all certificates, but that's not even remotely secure.

**Comment by timler** [comment]
This really helped me identify why `remote_image_url` worked fine on my dev machine (uploading the image from the URL specified) but not on my live server.

My scenario is probably a bit different, because I'm hosting the images on my own server, but I'll add some more details below in case they can help someone else in the future.

I am using Cloudflare to implement SSL for my server and ran into a couple issues where I was accessing the server directly (not via Cloudflare). If you're using a Cloudflare SSL certificate you rely on Cloudflare to add the intermediate and root certificates - accessing your server directly will result in SSL certificate errors.

I found that on my live server I had linked my domain name to the server IP address (in /etc/hosts) - required for a reverse proxy I have for the Wordpress blog - and when the live server was trying to download the images it was accessing them from the server directly not via Cloudflare.
