### ISSUE TITLE
Filename with spaces issue

### ISSUE THREAD

**Issue by flynfish** [carrierwaveuploader/carrierwave#1494]
I'm trying to set the `remote_{attribute)_url` with a url that has spaces in the filename. When the file is uploaded the filename is now different and includes `_20` rather than a space. 

example original filename: `Screen Shot 2014-10-26 at 9.31.44 PM.png`
when its uploaded to s3, it now becomes: `Screen_20Shot_202014-10-26_20at_209.31.44_20PM.png`

I've tried `remote_artifact_url = URI.decode(my_remote_url)` but that doesn't do anything. Is this a bug or am I doing something wrong?

**Comment by rgonsalves** [comment]
I am seeing a similar also in Rails 4.2 but not in 4.1.8.

**Comment by ruckus** [comment]
I'm seeing this same behavior on Rails 4.2.1 and CarrierWave 0.10.0.

I tried @rgonsalves suggestion of:

```
CarrierWave::SanitizedFile.sanitize_regexp = /[^a-zA-Z0-9\.\-\_\s]/
```

and that didnt seem to do the trick.

**Comment by stevesuh** [comment]
I'm getting the same behavior.

**Comment by balloob** [comment]
S3 doesn't support spaces. You will have to store the original filename as described in [the wiki](https://github.com/carrierwaveuploader/carrierwave/wiki/How-to:-Create-random-and-unique-filenames-for-all-versioned-files#saving-the-original-filename). Then when serving the file to the user, set the correct header to set the correct name.

**Comment by pmichna** [comment]
Has anyone solved the problem? I have tried saving the original filename as [described in the wiki](https://github.com/carrierwaveuploader/carrierwave/wiki/How-to:-Create-random-and-unique-filenames-for-all-versioned-files#saving-the-original-filename). However, the filename is already with underscore instead of space.

**Comment by kyleboe** [comment]
My solution was to set the sanitize file regular expression as follows:
```ruby
CarrierWave::SanitizedFile.sanitize_regexp= /[^a-zA-Z0-9\.\-\+\%_]/
```
As well as ensuring that the URL I was setting `remote_{attribute)_url` to was already URI encoded. Example:
```ruby
model.remote_file_url = URI.encode(my_remote_file_url)
```
In the uploader, I could then define the `filename` method to this:
```ruby
def filename
  URI.decode(original_filename) if original_filename.present?
end
```

I'm sure there is a better way (feel free to post if you know of one), this is just what worked for me. 

I am using Rails 4.2.10, Ruby 2.3.4, and CarrierWave 0.11.2 (maybe this was fixed in newer versions, didn't have time to dig through the newer codebases).

**Comment by kyleboe** [comment]
Also, @balloob as of this posting, S3 does support spaces in file names. Maybe that has changed in the last several months but storing files with whitespace in the file name works just fine for me.

**Comment by mshibuya** [comment]
#2131 should have fixed this.
