### ISSUE TITLE
Rails 4.1.8 + default_url fallback raises an error

### ISSUE THREAD

**Issue by freezepl** [carrierwaveuploader/carrierwave#1501]
Hi,
I have in image_uploader:

``` ruby
  def default_url
    ActionController::Base.helpers.asset_path("fallback/" + [version_name, "chat_image_default.png"].compact.join('_'))
  end
```

And on edit form:

``` haml
= image_tag @chat.image.thumb.url if @chat.image
```

Then it throws an error:

```
Asset names passed to helpers should not include the "/assets/" prefix. Instead of "/assets/fallback/thumb_chat_image_default.png", use "fallback/thumb_chat_image_default.png"
```

which I can solve by removing "ActionController::Base.helpers.asset_path".

**Problem is, when I am using Backbone templates I need to have whole path, with '/assets/' part.**
But since there is no 'assets' part, link is broken...

Can You help?
Thanks!

**Comment by cantonic** [comment]
I have the same issue. The newer version of sprockets doesn't want file paths including the `/assets/` prefix to be passed to helpers like `image_tag`. I changed the `default_url` method to:
```ruby
def default_url
  "dummy/"+[version_name, "dummy.png"].compact.join('_')
end
```

but the new problem is: when I do `@user.avatar.url` without `image_tag` i will get errors like `No route matches [GET] "/posts/2/dummy/dummy.png"` which is really annoying. I then have to change it to `ActionController::Base.helpers.image_path @user.avatar` in order to make it work. Since this seems to be how sprockets will be working in the future, is there a chance that carrierwave could adjust to it in a future version?

**Comment by chaixl** [comment]
Have the same issue after upgrading sprockets-rails to 2.1.4.  default_url should return different url inside view template and outside ( for API ).  Any solutions?

**Comment by zoopyserg** [comment]
The solution:
````ruby
  def default_url(*args)
    [version_name, "default_avatar.png"].compact.join('_')
  end
````
(note, no `/images` before the filename, as it looks for an asset inside images folder by default).
