### ISSUE TITLE
Error validating corrupted files on upload

### ISSUE THREAD

**Issue by richessler** [carrierwaveuploader/carrierwave#1512]
Similar to closed issues #386 #636, I'm coming across an issue where CW is not validating corrupted files correctly.

Work flow is something along: Have a .pdf,
                                                 manually change extension to .jpg,
                                                 upload file,
                                                 'file' uploads as broken image.

CW is raising the following:
```
CarrierWave::ProcessingError: Failed to manipulate with MiniMagick, Maybe it is not an image? Original 
Error: Command ("identify -quiet -ping /tmp/mini_magick20141129*1937*191ytmy.jpg") failed: {status_code=>1, :output=>"identify: Not a JPEG file: starts with 0x00 0x00 `/tmp/mini_magick20141129-1937-191ytmy.jpg' @ error/jpeg.c/EmitMessage/252.\n"}
```

**Comment by eavgerinos** [comment]
CarrierWave uses, by default, the only the file extension to guess the content type of the file. Therefore, you may feed it any kind of file (text, archive, mp3, whatever) with an extension of an image (png, jpg, etc.) and if you have included the MiniMagick module, it will try to perform processing operations on this file, ending up blowing like you stated above.

In order to avoid this you need to write a custom module that overrides `set_content_type` and use the unix `file` command or the https://github.com/blackwinter/ruby-filemagic gem to properly get the actual content type of the file.
