### ISSUE TITLE
Rails 4.2 support problem

### ISSUE THREAD

**Issue by krim** [carrierwaveuploader/carrierwave#1576]
DEPRECATION WARNING: Currently, Active Record suppresses errors raised within `after_rollback`/`after_commit` callbacks and only print them to the logs. In the next version, these errors will no longer be suppressed. Instead, the errors will propagate normally just like in other Active Record callbacks.

You can opt into the new behavior and remove this warning by setting:

  config.active_record.raise_in_transactional_callbacks = true

 (called from mount_base at /home/krim/.rvm/gems/ruby-2.2.0/bundler/gems/carrierwave-79b8e2496d94/lib/carrierwave/orm/activerecord.rb:59)

**Comment by bensie** [comment]
You can just opt-in to the new behavior as it suggests. There aren't any places in CarrierWave where we expect a `raise` to be suppressed.

**Comment by nasirvq** [comment]
Hey guys, 

I am getting the same error in my rails app. It looks like the problem is in https://github.com/carrierwaveuploader/carrierwave/blob/52beaa1ebec56b9649b6e1f46366030e3e39c2bd/lib/carrierwave/orm/activerecord.rb#L57 

line # 57, 58, and 61. (http://prntscr.com/9py2al)

Any chance if this could be fixed? Thanks

**Comment by bensie** [comment]
@nasirvq See my comment above. It's a deprecation warning that is out of our control. Opt-in to the new behavior in your app and it should go away.
