### ISSUE TITLE
Same random filename for both original and version in Carrierwave

### ISSUE THREAD

**Issue by davidmles** [carrierwaveuploader/carrierwave#1587]
I'm using Carrierwave to upload an image which is not related to any model, so I'm using a standalone uploader.

I want to set the same random filename for both the original and version files.

This is my relevant controller code:

```ruby
def upload
  image = params[:files].first
  uploader = ImageUploader.new
  uploader.store!(image)
end
```

And this is my standalone uploader:

```ruby
 class ImageUploader < CarrierWave::Uploader::Base
    storage :file

    version :normal do
      process resize_to_limit: [640, 640]
    end

    def extension_white_list
      %w(jpg jpeg gif png)
    end

    def random_filename
      @random_filename ||= SecureRandom.hex
    end

    def filename
      "#{random_filename}.#{file.extension}"
    end

    def store_dir
      'uploads/images'
    end
  end
```

This generates these two files:

- 9ab798e73ffc2c586ca4541ed3dde574.jpg
- normal_7a699c1641fc4e9d41d00a848ab09117.jpg

Is this a bug? Shouldn't the normal version have the same name?

**Comment by eavgerinos** [comment]
@davidmles True.

This happens because CarrierWave creates an anonymous class out of the Uploader class for each version, this can be seen [here](https://github.com/carrierwaveuploader/carrierwave/blob/master/lib/carrierwave/uploader/versions.rb#L69). As a result of this, the instance of the uploader you invoked `store!` is not the one that handles the version management, and the instance variable `@random_filename` is nil during the instantiation.

I don't have much time during weekdays, so I'd be more than happy if you want to send a PR for this, else I'll look at it as soon as possible!

Thanks for reporting!

**Comment by eavgerinos** [comment]
Till these is fixed, I found a workaround I'm going to add in the README.

You can pass an object to the uploader in order to serve as a model.

```Ruby
class ImageUploader < CarrierWave::Uploader::Base
  include CarrierWave::MiniMagick

  storage :file

  version :normal do
    process resize_to_limit: [640, 640]
  end

  def extension_white_list
    %w(jpg jpeg gif png)
  end

  def store_dir
    'uploads/images'
  end

  def filename
    "#{random_filename}.#{file.extension}"
  end

  protected
  def random_filename
    var = :"@filename"
    model.instance_variable_get(var) ||
      model.instance_variable_set(var, SecureRandom.hex)
  end
end

class DummyModel
  attr_accessor :filename
end
```

And when you upload the file you pass the instance of DummyModel in to the uploader's constructor

```Ruby
model = DummyModel
image = File.open("a_file_here")
uploader = ImageUploader.new(model)
uploader.store!(image)
```
