### ISSUE TITLE
What criteria are used to validate a remote url?

### ISSUE THREAD

**Issue by morenoh149** [carrierwaveuploader/carrierwave#1610]
I've searched through the code and couldn't find anything obvious. I have many urls to images that are working without problems. But this one `http://journal.paul.querna.org/wp-content/uploads/2010/06/nodejs.png` is there anything obviously wrong with this url? or perhaps its an issue with the binary it points to?
[gist](https://gist.github.com/morenoh149/c96aa6e3ba5c87e095bd)

reading this https://github.com/carrierwaveuploader/carrierwave#uploading-files-from-a-remote-location it'd be great to know what criteria would prevent successful model creation.

**Comment by morenoh149** [comment]
Inspecting the `errors` property on the failed model reveals the answer.
```
 [5] pry(main)> bad_room.errors
=> #<ActiveModel::Errors:0x007fade7ccfac8
 @base=
  #<Room:0x007fade7cfe260
   id: nil,
   name: "Node.js",
   topic: nil,
   created_at: nil,
   updated_at: nil,
   icon: nil,
   slug: "node-js">,
 @messages=
  {:icon=>
    ["could not download file: redirection forbidden: http://journal.paul.querna.org/wp-content/uploads/2010/06/nodejs.png -> https://journal.paul.querna.org/wp-content/uploads/2010/06/nodejs.png"]}>
```
Don't know if the docs could be improved in this regard.

**Comment by eavgerinos** [comment]
@morenoh149 This is a limitation of the [open-uri](https://github.com/carrierwaveuploader/carrierwave/blob/master/lib/carrierwave/uploader/download.rb#L40) because it cannot follow the redirects. As you can see, the url you passed to the `remote_image_url` does an http -> https redirection.

A workaround for this is, before feeding a url to the `remote_image_url` method, you can perform a `HEAD` request to the url, following the redirections, and get its `last effective url` in order to pass this to `remote_image_url`

**Comment by morenoh149** [comment]
ah very good. I think I'll instead just supply a default image.

**Comment by morenoh149** [comment]
@eavgerinos wait so I added a default image to my uploader but it's not being used here. Is there a way for me to catch the model creation failure and provide the default image as a falllback?
