### ISSUE TITLE
How to access an instance variable in a version?

### ISSUE THREAD

**Issue by jhorsch** [carrierwaveuploader/carrierwave#1612]
I was wondering how to use an instance variable from a method called before the cache.

Specifically, I would like to use the @crop_ratio variable set in 'determine_crop' inside the 'enlarged version' method.

    photo.rb
    attr_accessor :image_width, :image_height

    product_uploader.rb
    before :cache, :determine_crop

    version :enlarged do
       #how can I access this instance variable from the 'determine_crop' method
       if @crop_ratio > 3
          process :resize_to_fill => [1500,1000]
       else
          process :resize_to_fill => [1500,500]
        end
    end

    def determine_crop(new_file)

       if model.image_width.nil? || model.image_height.nil?
         model.image_width, model.image_height = `identify -format "%wx %h" #{new_file.path}`.split(/x/).map { |dim| dim.to_i }
       end

       w = model.image_width
       h = model.image_height

       w > h ? @crop_ratio = w.to_f / h : @crop_ratio = h.to_f / w

    end

**Comment by eavgerinos** [comment]
__Please post usage questions to Stack Overflow.__

You cannot access an instance variable from a version, since version uses a different (anonymous) class and instance of the uploader. For more details please look [here](https://github.com/carrierwaveuploader/carrierwave/issues/1587).

You should set an instance variable to the model if you want it to be accessible to all versions.
A similar tutorial is [this](https://github.com/carrierwaveuploader/carrierwave/wiki/How-to:-Create-random-and-unique-filenames-for-all-versioned-files).
