### ISSUE TITLE
Authenticated URL generation kills cache

### ISSUE THREAD

**Issue by ali-nawaz** [carrierwaveuploader/carrierwave#1678]
Whenever we call the url method for an uploader, given that the ACL is private, a new URL is generated every time, killing the browser cache. I guess it would be really nice to add a support for cache URLs like if I have URL expiration set to 24 hours I should get the same URL for 1 day, to support browser caching and saving the bandwidth cost of S3.
Here the Time.now is used https://github.com/carrierwaveuploader/carrierwave/blob/master/lib/carrierwave/storage/fog.rb#L193 which is the source of the problem.

Thanks.

**Comment by bensie** [comment]
This is not an issue with CarrierWave. 

As far as I know, even if you set the time to the same time, calling the method to generate an authenticated URL will still give you a new URL because of the way AWS signs URLs. You would need to store/cache the URL you get back on your end if you want to reuse URLs across a 24-hour period.
