### ISSUE TITLE
produce generated url for STI class

### ISSUE THREAD

**Issue by krismp** [carrierwaveuploader/carrierwave#1744]
I have 1 STI class inherits from `User` class

    class User < ActiveRecord::Base
      mount_uploader :avatar, AvatarUploader
    end
    
    class Staff < User
    
    end

but when I looping all the staffs user including the image url like this:

**controller**

    @staffs = Staff.all

**view**

    <ul>
    <% @staffs.each do |staff| %>
    <li>
      <%= staff.name %>
      <%= image_tag staff.avatar_url(:small) %>
    </li>
    <% end %>
    </ul>

this code:

    <%= image_tag staff.avatar_url(:small) %>

still generated upload url like this:

    /uploads/user/avatar/44/avatar1.jpg

instead of

    /uploads/staff/avatar/44/avatar1.jpg

How to do this? thank you

**Comment by thomasfedb** [comment]
Hi @krismp 

Please see the README section on [changing the storage directory](https://github.com/carrierwaveuploader/carrierwave#changing-the-storage-directory). You can use a reference to your `model` in order to use the model class to set the directory.

I would however advise against doing so unless you have an incredibly good reason to do so.
