### ISSUE TITLE
version_name nil in sublcass

### ISSUE THREAD

**Issue by aesnyder** [carrierwaveuploader/carrierwave#1957]
```
class ImageUploader < CarrierWave::Uploader::Base
  include CarrierWave::MiniMagick

  process :resize_to_fit => [1024, 1024]

  version :mini do
    process :resize_to_fit => [24, 24]
  end

  version :small do
    process :resize_to_fit => [48, 48]
  end

  version :medium do
    process :resize_to_fit => [72, 72]
  end

  version :large do
    process :resize_to_fit => [128, 128]
  end
end

class AvatarUploader < ImageUploader
  def default_url
    "/assets/default_icon_#{version_name}.png"
  end
end
```

My issue is that `version_name` ends up being `nil` when in a subclass. 

The following does work:

```
class AvatarImgUploader < CarrierWave::Uploader::Base
  include CarrierWave::MiniMagick

  process :resize_to_fit => [1024, 1024]

  version :mini do
    process :resize_to_fit => [24, 24]
  end

  version :small do
    process :resize_to_fit => [48, 48]
  end

  version :medium do
    process :resize_to_fit => [72, 72]
  end

  version :large do
    process :resize_to_fit => [128, 128]
  end

  def default_url
    "/assets/default_icon_#{version_name}.png"
  end
end
```

This feels like a bug. If not, can you point me in the right direction please?

**Comment by zhengpd** [comment]
Facing the same problem here: subclass give nil `version_name`.

**Comment by tbrammar** [comment]
It seems like by design CarrierWave[ sets the class that the version is defined in to the object before processing](https://github.com/carrierwaveuploader/carrierwave/blob/master/lib/carrierwave/uploader/versions.rb#L69), even if called from a subclass.

This causes the issue you mentioned above as well as issues around setting various attributes. You can see a longer discussion [here](https://github.com/carrierwaveuploader/carrierwave/issues/1064). As it's been set as "by design" I don't think they're going to change this approach.
