### ISSUE TITLE
SanitizedFile should support read with an optional length and output_buffer arguments

### ISSUE THREAD

**Issue by jcoyne** [carrierwaveuploader/carrierwave#1959]
Then it would conform to the IO api as documented here: http://ruby-doc.org/core-2.2.2/IO.html#method-i-read

Presently if I have this code:

```
cwf = Carrierwave::SanitizedFile.new
out = File.new
IO.copy_stream(cwf, out)
```

Then I get this error:

```
     ArgumentError:
       wrong number of arguments (given 2, expected 0)
     # /Users/jcoyne/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/carrierwave-0.11.2/lib/carrierwave/sanitized_file.rb:157:in `read'
```

**Comment by janko-m** [comment]
@jcoyne Two years ago I tried changing `CarrierWave::SanitizedFile#read` to conform to the IO interface, because I wanted to build a Flickr storage gem, where the Flickr client used Faraday which required these two parameters. When I thought it could maybe work, a lot of tests were failing for unknown reasons, and it was a bit intimidating that `CarrierWave::SanitizedFile` can have so many states, which `#read` also changes. It really can be [this simple](https://github.com/janko-m/shrine/blob/86e268b8b893db8ec68e7c2720b34cf948cc148d/lib/shrine.rb#L696-L698).
