### ISSUE TITLE
Support for ActiveRecord dup method

### ISSUE THREAD

**Issue by frostme** [carrierwaveuploader/carrierwave#1962]
It would be great if carrierwave would be able to fully support ActiveRecords dup method. For example,

if I have the following model

``` ruby
class ExampleModel < ActiveRecord::Base
  mount_uploader :file, FileUploader
end
```

then i'd be able to do the following

``` ruby
current = ExampleModel.find 1
new_model = current.dup
new_model.save
```

And the file would be copied and saved over to the new model.

**Comment by brentdodell** [comment]
@frostme, is your experience that you get an `output error: #<TypeError: can't convert nil into Integer>` when trying to `dup` an ActiveRecord model with a Carrierwave image attached?

I'm seeing that and as best I can tell, it's coming from Carrierwave. My guess is because Carrierwave is relying on the object id, but the object isn't saved yet on `dup`.

**Comment by brentdodell** [comment]
FWIW, I'm not sure what I would expect when `dup`ing an object with a CarrierWave uploader mounted to it. I don't know if I'd expect the file to be `nil`ed out, or to have a new instance of the file that would get updated on save. I would however expect it to not throw an error, preventing me from `dup`ing.
