### ISSUE TITLE
Uploading other images when getting error

### ISSUE THREAD

**Issue by Rubioli** [carrierwaveuploader/carrierwave#2012]
In my application I use `nested_forms` and my `file_field :image` is inside all the added nested forms. I usually have 30+ nested forms and 30+ image uploads.

Problem now is that when I `submit` a post, sometimes I get error on some images _(Files looks like to be another format)_. Issue now is that instead of uploading all other images that hasn't got any error, it _empties_ all the `file_field :image` fields.

How can I make it so if **2 out of 30** has error, it still **upload/keep** other 28 images without error and just _give me error/empty_ on those 2, so I don't need to find and upload the images again and again.

Thanks in advanced!

**Comment by paweljw** [comment]
@Rubioli , have you tried adding cache fields to your form, like it's shown in [Making uploads work across form redisplays](https://github.com/carrierwaveuploader/carrierwave#making-uploads-work-across-form-redisplays)?

**Comment by Rubioli** [comment]
Thanks 👍

**Comment by Rubioli** [comment]
It does work fine on some of my images. I use `nested_forms` inside my form and it doesn't cache those in my `nested_forms`.

_Here is my code:_


```
# Slide model
class Slide < ActiveRecord::Base
     mount_uploader :image, ImageUploader
end
```

```
# _slide_fields.html.haml view for nested forms
= f.file_field :image
= f.hidden_field :image_cache
```

I have also added `:image_cache`, in my **PostsController** `post_params` for **slides params**.

Something I have missed?

**Comment by paweljw** [comment]
AFAIR the file fields themselves will not remain filled out with paths after a form reload, but rather the cache will be uploaded if the file field is empty when the form is eventually saved.

In the section I linked above, there's a suggestion to use a thumbnail of the cached/uploaded image to signal to the user that the upload itself completed successfully:

```
<label>My Avatar</label>
    <%= image_tag(@user.avatar_url) if @user.avatar? %>
```

While I understand that this might not be what you want as your end result, could you try displaying e.g. ```f.object.image_url``` in your form (in development mode, of course), so that we can ensure that the upload itself is working? If the cache works, the URLs should show up even when the file fields are seemingly empty. Then it will simply be a matter of you deciding how to inform the user that the form will, in fact, do what they wanted after fixing other problems with it (those that prevented the form from saving in the first place).

If the URLs do not show up, it will mean that the image is not cached correctly and we can work from there.

**Comment by Rubioli** [comment]
Thanks for your help.

Both `new` & `edit` actions use the same `_slide_fields.html.haml` file with same codes. But for some reason it works in `new` action and not in `edit` action when updating a image.

**Comment by paweljw** [comment]
Let's pause for a second here so I can understand well what is happening. After creating the parent object for Slides you edit it. Then the images are missing? By which I mean - similar to what I meant before - that `f.object.image?` is false? Or does the validation (meaning, the `update` action) need to fail before images don't work?

**Comment by Rubioli** [comment]
When I add a post and go and edit them, the "already" uploaded images are not missing and show as they normally would, but when adding new `slides` (in `edit - update` action) cache for those slides doesn't work as it does in `new - create` action.

**Comment by varvaray** [comment]
+ 1, have the same issue. Are there any updates on that one?

**Comment by yangjindong** [comment]
+1 same issue

**Comment by mshibuya** [comment]
It looks rather a usage question, if you can provide fully runnable reproducible app I can help you.
