### ISSUE TITLE
Excon::Errors::SocketError - Broken pipe

### ISSUE THREAD

**Issue by krzkrzkrz** [carrierwaveuploader/carrierwave#203]
UserUploader has:
class UserUploader < CarrierWave::Uploader::Base
include CarrierWave::MiniMagick
storage :s3

Gem file has:
gem 'carrierwave'
gem 'fog'
gem 'mini_magick'

Bundle shows: Using carrierwave (0.5.1) 

When I try to upload an image, I get:
Excon::Errors::SocketError in Admins/usersController#update
Broken pipe

Anyone coming across the same error?

**Comment by jogiranjith** [comment]
@marcamillion Can you please specify what access to be given to i am user .

**Comment by marcamillion** [comment]
@jogiranjith -- I can't tell you what access you should give to your user, because it depends on what your app (and user) should do. I can say what I did:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:PutObjectAcl",
                "s3:GetObject",
                "s3:DeleteObject"
            ],
            "Resource": [
                "arn:aws:s3:::myapp/*"
            ]
        }
    ]
}
```
I only wanted to give the user the ability to do basic stuff (uploading, reading and deleting objects) in S3 -- which is what the above IAM rules facilitate. That user can't list the bucket, or access any other AWS resources in my account or anything like that.

Hopefully this gives you some direction.

**Comment by jogiranjith** [comment]
@marcamillion thanks marc this helped me.
