### ISSUE TITLE
#{column}_url equals to nil after saving object

### ISSUE THREAD

**Issue by virolea** [carrierwaveuploader/carrierwave#2253]
I came across an issue trying to save an image. I'm submitting a form with an image, and update an existing record with it. I'm doing through an xhr request from the client, and I want the request to send the image url back.

    def update
      record = Record.find(params[:id])
      record.update(photo: params[:photo])
      render json: record.photo.url, status: :ok
    end

 Carriewave's doc specifies: 
    
    u = User.new
    u.avatar = params[:file]

    u.save!
    u.avatar.url # => '/url/to/file.png'

Will help me get my file url. However my action returns nil but it works if I instantiate a new version of the record:

I did some testing in the console to show my point:
![capture d ecran 2017-11-23 a 15 06 45](https://user-images.githubusercontent.com/3525369/33176720-56a16182-d060-11e7-9f27-9c2dd3699dff.png)

So the only way I can get the url of the image without having to fetch the record again, after having a look at the uploader object is through:
    
    c.photo.metadata['url']
    # => returns the url

Config:
   Rails 5.1.4
   Carrierwave 1.2.1

**Comment by gjamerson** [comment]
I'm having the same issue. 
Rails 4.2.10
Carrierwave 1.2.1

**Comment by rbclark** [comment]
I believe I am experiencing this exact same issue and it seems to be exhibiting itself inside of my test suite. I hand off to a background worker where the ProductTest is updated and then have been running the following commands to compare the response.

    pt.reload
    => nil
    pt == ProductTest.last
    => true
    pt.patient_archive.file
    => nil
    ProductTest.last.patient_archive.file
    => #<CarrierWave::SanitizedFile:0x00007fd07bc67a20
     @content_type=nil,
     @file="/path/to/rails/public/data/upload/product_test/5ab4243dc60ac1cce7e23546/product_test-5ab4243dc60ac1cce7e23546.zip20180322-52455-1dmh03x",
     @original_filename=nil>
    pt.patient_archive.file
    => nil

It seems that the reload is not properly refreshing the file, even though it did previously on Carrierwave  (0.11.2) and carrierwave-mongoid (0.9.0)

I was originally going to post this on carrierwave-mongoid however it seems this issue already closely resembles my issues so I'm unsure if the issue is here or carrierwave-mongoid.

This is now happening for me one
rails (4.2.10)
carrierwave (1.2.2)
carrierwave-mongoid (1.0.0)

**Comment by rbclark** [comment]
Just wanted to bump this and see if there is any other info I can provide to help get this issue fixed? It is blocking a few other tasks I have so if there is anything I can do or provide please let me know.

**Comment by danderozier** [comment]
I seem to be having the same issue in Rails 5.2 and Carrierwave 1.2.2. The object returned after saving returns `nil` for the url, but instantiating a new object for the same record works as expected.

**Comment by Virolea** [comment]
I might have a look at the code and submit a PR if I find the time. 
Now that rails 5.2 and active storage are out, I might move from carrierwave in the near future

**Comment by p8** [comment]
I think the problem is in the following code:

https://github.com/carrierwaveuploader/carrierwave/blob/97c028cc0ee8e6e84a3b60ae60fd4f59703f8a40/lib/carrierwave/mounter.rb#L35

```
def uploaders
      @uploaders ||= read_identifiers.map do |identifier|
        uploader = blank_uploader
        uploader.retrieve_from_store!(identifier) if identifier.present?
        uploader
      end
end```

When a model is initialized before the identifier is set `retrieve_from_store!` will not be called because  `@uploaders` is already set.

This did work differenlty in `0.11`:
```
      def uploader
        @uploader ||= record.class.uploaders[column].new(record, column)
        @uploader.retrieve_from_store!(identifier) if @uploader.blank? && identifier.present?
        @uploader
      end
```

**Comment by p8** [comment]
Unsetting the `@uploaders` instance variable on the mounter seems to fix it.
```
    attachment.url # => nil    
    _mounter(:attachment).instance_variable_set(:@uploaders, nil)
    attachment.url # => the correct url
```

**Comment by mshibuya** [comment]
I don't understand what makes the attribute and `@uploaders` out of sync.
Can anyone reproduce this using a vanilla Rails app?

**Comment by mshibuya** [comment]
Stale, please reopen on update.
