### ISSUE TITLE
content_type_whitelist not working

### ISSUE THREAD

**Issue by jedrekdomanski** [carrierwaveuploader/carrierwave#2301]
The documentation says:
"The same thing could be done using content types. Let's say we need an uploader that accepts only images. This can be done like this"

```
class MyUploader < CarrierWave::Uploader::Base
  def content_type_whitelist
    /image\//
  end
end
```
I set it like this so I should get `content_type_whitelist_error: "You are not allowed to upload %{content_type} files"` but I get `mini_magick_processing_error: "Failed to manipulate with MiniMagick, maybe it is not an image? Original Error: %{e}"` error because carrierwave is trying to perform an operation on a file that is not an image and because carrierwave does not check what file it is. So it looks like defining `content_type_whitelist` does not work.

**Comment by jedrekdomanski** [comment]
I thought that the browsers change content type of files, however I tried it in the console.
`file -I pdf_asJPG.jpg` => `text/plain; charset=us-ascii`
`rails c`
`f = File.open("spec/fixtures/files/pdf_asJPG.jpg")`
`photo_uploader = PhotoUploader.new`
`photo_uploader.cache! f`
`CarrierWave::ProcessingError: Failed to manipulate with MiniMagick, maybe it is not an image?`
How does Carrierwave infer the content type? By extension? It looks like it changes the content type somehow.

Anyway, doing something like:
```
class MyUploader < CarrierWave::Uploader::Base
  def content_type_whitelist
    /image\//
  end
end
```
makes no sense at the moment.

**Comment by mwgalloway** [comment]
By default if the object passed in to the uploader responds to the method "content_type" then it will use the result of that method. Otherwise it uses the [mime-types gem](https://github.com/mime-types/ruby-mime-types) which determines the content type based upon the file extension.

If you need the whitelist to be validates by the content of the file you'll want to install the [ruby-filemagic gem](https://github.com/blackwinter/ruby-filemagic) and then:
`require 'carrierwave/uploader/magic_mime_whitelist'
and in your uploader include:
`include CarrierWave::Uploader::MagicMimeWhitelist`

Doing this will instead use the ruby-filemagic gem to determine the content type which actually scans the file to make a determination rather than uses the extension. Unfortunately, it doesn't look like this feature of carrierwave is really documented anywhere, I just found it by digging around the gem and reading code comments.

**Comment by jedrekdomanski** [comment]
Unfortunately, I have just tried that and it still tries to perform operations on a file that is not an image and throws processing error so it does not scan for the content type of the file but determines the content type by extension. Any ideas?

**Comment by pnghai** [comment]
I see that MagicMimeWhitelist is no longer exist. How do you resolve the problem of content type detection?

**Comment by mshibuya** [comment]
Using `content_type_whitelist` will be enough, MagicMime detection is performed by default now.
https://github.com/carrierwaveuploader/carrierwave#cve-2016-3714-imagetragick
