### ISSUE TITLE
mount_uploader support condition?

### ISSUE THREAD

**Issue by insub** [carrierwaveuploader/carrierwave#2477]
I want to be able to write url string directly to the  'avatar' field when creating an 'user' object without actual upload. Because I have prepared a batch of default avatars on cloud storage.

I tried to use 'skip_callback' when creating user objects, but it didn't work.
What's the right way?

At the same time, I think it might be a good idea if mount_uploader to support conditional options? Maybe like:

`mount_uploader :avatar, AvatarUploader, on: [create, update]`
or
`mount_uploader :avatar, AvatarUploader, if: some_condition`

**Comment by mshibuya** [comment]
Use of [#update_column](https://api.rubyonrails.org/classes/ActiveRecord/Persistence.html#method-i-update_column) enables you to populate the file location into the column value directly.

> mount_uploader to support conditional options

That's not possible, because uploaders need to be in place before the persistence operation (create/update) happens.
