### ISSUE TITLE
`mount_on` not set in uploader

### ISSUE THREAD

**Issue by ankane** [carrierwaveuploader/carrierwave#2478]
Hey, thanks for creating and maintaining this great gem all these years!

It looks like uploaders have a `mount_on` method, but it's not set with Active Record.

```ruby
class User < ApplicationRecord
  mount_uploader :avatar, AvatarUploader, mount_on: :image
end

user.avatar.mounted_as # :avatar
user.avatar.mount_on # nil instead of :image
```

Here's a failing test case to demonstrate: https://github.com/carrierwaveuploader/carrierwave/compare/master...ankane:mount_on

**Comment by t-mangoe** [comment]
I think that `mount_on` may be an option instead of a method.
`mounted_as` is declared as an instance variable in `mountable.rb`.
https://github.com/carrierwaveuploader/carrierwave/blob/3084b24257dd309ee00ff350067c8c6e985ad1bc/lib/carrierwave/uploader/mountable.rb#L31-L34
But, it looks like `mount_on` is not declared.

**Comment by ankane** [comment]
Thanks @t-mangoe! (and sorry it took so long to follow up)
