### ISSUE TITLE
Image Not Uploading upon upgrade to 2.1.0

### ISSUE THREAD

**Issue by joshmenden** [carrierwaveuploader/carrierwave#2482]
Hello 👋🏼

I recently upgraded my carrierwave version from 1.2.0 to 2.1.0. I am using `fog` (AWS) for `storage` and, after following the instructions [in this issue](https://github.com/carrierwaveuploader/carrierwave/issues/2413), I set `cache_storage =:file`.

However, I am still seeing unexpected behavior. The image _does_ save locally to the cache under the expected folder, and when I set the image, and call `my_model.uploader.cached?` it _does_ return the `cache_id`. Yet when I call `my_model.save!`, the image is not saved to the AWS `store_dir`, neither is the cache image removed.

I attempted to use `cache_storage: fog`, and have the same issue -- the image saves to an S3 cache bucket, but upon save, does not save to the intended directory.

I've been debugging locally and discovered that, when I call `my_model.save!` and the following method is called in the gem's `lib/carrierwave/uploader/store.rb`:

```
      def store!(new_file=nil)
        cache!(new_file) if new_file && ((@cache_id != parent_cache_id) || @cache_id.nil?)
        if !cache_only && @file && @cache_id
          with_callbacks(:store, new_file) do
            new_file = storage.store!(@file)
            if delete_tmp_file_after_storage
              @file.delete unless move_to_store
              cache_storage.delete_dir!(cache_path(nil))
            end
            @file = new_file
            @cache_id = @identifier = nil
            @staged = false
          end
        end
      end
```

The `@cache_id` is nil. I'm assuming that has something to do with the fact that it then does not save the image nor delete the cache.

Please advise on how to proceed. I'd be happy to submit a PR for the issue but I need a little bit of guidance on where in the carrierwave code I should look for the issue.

**Comment by DaniG2k** [comment]
Experiencing a similar issue here, after upgrading to Carrierwave from 1.2.0 to 2.1.0

**Comment by pomu0325** [comment]
I also had a same issue, but finally found that culprit is in my code.
I was `reload`ing the record within the transaction.

Mounters, which retains uploaded files as a cache, are also reset upon `reload`: 
https://github.com/carrierwaveuploader/carrierwave/blob/2a0fefcd7762f91292fbc84911fc91f142699766/lib/carrierwave/orm/activerecord.rb#L92-L94

CarrierWave 2.x now uploads file to the store at `after_commit`( https://github.com/carrierwaveuploader/carrierwave/pull/2209 ), not at `after_save` as in 1.x. 

So `reload`ing before commit causes files not to be uploaded.

I hope it helps :)
