### ISSUE TITLE
Completely migrate from whitelist/blacklist to allowlist/denylist terminology

### ISSUE THREAD

**Issue by mshibuya** [carrierwaveuploader/carrierwave#2536]
The work done in #2442 is just a half-way. It leaves names of some classes and methods untouched for smoother transition. In the next major release we will migrate all of them.

**Comment by seuros** [comment]
Hi, i think we should discard the denylist and have only allowed list . My point is there is always a security holes when a dev restrict instead of allowing things .

**Comment by mshibuya** [comment]
@seuros OK, I'll mark the denylist as deprecated, so we can remove it in the future.

**Comment by zzak** [comment]
@mshibuya Do you have a timeline when `allow_denylist` will be removed? I would like to find an alternative if possible, because I don't consider it a "security hole" if we intend to accept any kind of file upload using carrierwave.

There is no good solution, I've tried this:

```
  def extension_allowlist
    [
      Regexp.new("\\A(?!#{Regexp.union(uploader_denylist).source}).*")
    ]
  end
```

But I think it's not unreasonable to allow this behavior if the developer wants it -- I can understand if it's not default however.

**Comment by mshibuya** [comment]
I don't have a specific due date, but the removal is likely to happen on the release of the next major release 4.0.0.

By the way, I want to understand your usecase better.

> if we intend to accept any kind of file upload using carrierwave

I see, but why is it so hard to list up all the allowed extensions? What sort of extensions need to be denied?

**Comment by zzak** [comment]
> why is it so hard to list up all the allowed extensions? What sort of extensions need to be denied?

The problem is it is domain specific, there is a business need for it to allow uploading any file extension (we can't assume the user has used a new type of file, e.g. a 3d blueprint or something) and that decision should be ours to make.

I can understand if the default behavior is to raise on disallow as a possible attack vector, but if you're 100% aware of the risks and handling those cases in your business domain, there should be a path to support it. Or we need to write our own extension, which is an acceptable alternative.

**Comment by seuros** [comment]
From what I remember, if the list is not set.  Everything is accepted.

You use it only if you want to restrict the types.

**Comment by zzak** [comment]
I think we do want to disallow certain types, that is why we are seeing the deprecation warning, but there is a very specific reason to disallow those file types for user-experience, not to prevent malicious behavior.

I just don't see the point of deprecating a thing that doesn't outright introduce you to a vulnerability, is file upload an attack vector? I think you can put other guards in place like to prevent large payloads or when reading the file. If the developer decides to avoid safely handling user input, that is on them.
