### ISSUE TITLE
Delete a file in 3.0.0.beta - Breaking change

### ISSUE THREAD

**Issue by Drnoodle** [carrierwaveuploader/carrierwave#2654]
Hello 👋
In carrierwave `2.2.2` I was able to delete my file using `update!(myfile: nil)`.
After updating carrierwave to `3.0.0.beta` I have to use `update!(remove_myfile: true)` to delete my file.
I don't see this breaking change in [the changelog](https://github.com/carrierwaveuploader/carrierwave/blob/master/CHANGELOG.md).
I'm currently hesitating to downgrade carrierwave to `2.2.x` and wait for the next release before refactoring my code.
Let me know if you plan to keep the breaking change. 👍
Hugo

**Comment by mshibuya** [comment]
It was a side effect of #2613. Now fixed in the master.
But I consider this behavior of allowing file deletion by nil assignment is an accidental one brought by https://github.com/carrierwaveuploader/carrierwave/commit/67800fdeb796a7b2efe1192e06f619dcc3c64f05, not a part of public API design. I don't recommend relying on this.

**Comment by Drnoodle** [comment]
Thx!
