### ISSUE TITLE
undefined method `to_file' for #<CarrierWave::Storage::Fog::File:0x007fce2dddc4f0>

### ISSUE THREAD

**Issue by bokor** [carrierwaveuploader/carrierwave#725]
Getting this error on uploading a file with 0.5.8 and fog 1.3.1  Any ideas?

**Comment by chuckbergeron** [comment]
@hoenth Did this end up working out for you?

**Comment by hoenth** [comment]
Yes, quite well. Here is a gist with the validator code: https://gist.github.com/hoenth/960c9c00ae8acc2e88da

We use it like this
    validates :photo, :verify_cached_file => true

**Comment by chuckbergeron** [comment]
@hoenth Fantastic, thanks! Will give it a shot.

**Comment by brettshollenberger** [comment]
@hoenth I suppose it depends on how many servers you have, and therefore how likely it is you'll lose the user's file, but for what it's worth we're opting to always ask the user to re-upload files on validation error, because I think adding an additional extra round trip (2nd validation error in a row) sounds like an even worse experience than just asking for re-upload. Even if you only have 2 servers, you have a 50/50 chance the user will have this experience.

A better option still would be adding a shared file system for caching. EFS feels stupid expensive to pay per GB/hour, but if you make sure to delete your caches after successful upload, and sweep up once in a while, it could be basically free :)

**Comment by ollieh-m** [comment]
A solution to this is storing the cache files remotely, so both servers get the file from the same S3 or Rackspace storage. This is supported in Carrierwave 1.2 (but not < 1. I'm not actually sure when the feature was added). You can configure it like this for Rackspace and similar for S3:
```
config.fog_provider = 'fog/rackspace'
config.storage = :fog
config.cache_storage = :fog
config.fog_credentials = {
  provider:           'Rackspace',
  rackspace_username: ENV['RACKSPACE_USERNAME'],
  rackspace_api_key:  ENV['RACKSPACE_API_KEY'],
  rackspace_auth_url: Fog::Rackspace::UK_AUTH_ENDPOINT,
  rackspace_region:   :lon
}
config.fog_directory = Rails.env
config.cache_dir = "#{Rails.env}/tmp"
```
Obviously slows things down a bit to save the initial cache file remotely - but not significantly. Carrierwave handles deleting the cache file when the actual file is persisted.
