### ISSUE TITLE
Intermittent errors from CarrierWave when running tests in parallel

### ISSUE THREAD

**Issue by tamouse** [carrierwaveuploader/carrierwave#954]
This isn't really a bug but I don't know where else to turn at this point.

We use CarrierWave to move our assets up to S3. When we run our rspec tests in CI in serial fashion, everything works fine. However, when we run them in parallel, the tests fail intermittently , but always at a point where it is attempting to use CarrierWave. We are using version 0.5.8 of CW and Rails 3.1.3. Parallel is v. 0.5.20. I am just looking for some help here. Thanks.

**Comment by tom-lord** [comment]
Dear future readers,
I recently ran into this same issue. (Using a much newer version `0.8.0`!)

The issue is likely that your application is writing files to `/tmp/` or some folder relative to `Rails.root` - e.g. `"#{Rails.root}/public/tmp`. Two processes writing to the same file will probably run into trouble.

For more portable code, you can use Dir.tmpdir to automatically honour the TMPDIR environment variable:

```
# config/initializers/carrierwave.rb
CarrierWave.configure do |config|
  if Rails.env.production?
    # production setup stuff
  elsif Rails.env.test?
    config.storage = :file
    config.cache_dir = "carrierwave"
    config.root = Dir.tmpdir # <--------  !!!!  
  else
    # ....
  end
end
```
